name: Run R Script on Schedule

on:
  schedule:
    - cron: '10 04 * * *'
    # This schedules the job to run daily at midnight UTC
  push:
    branches:
    - main
    
jobs:
  run-r-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        ref: main  # Ensure the workflow checks out the main branch
        
    - name: Debug repository contents
      run: |
        ls -la  # List files in the repository to verify the R script is present

    - name: Set up R
      uses: r-lib/actions/setup-r@v2
      with:
        r-version: '4.2.2'  # Specify the R version you want to use
        
    - name: Install packages
      uses: r-lib/actions/setup-r-dependencies@v2
      with:
        packages: |
          any::tidyverse 
          any::googlesheets4
          any::timevis
          any::htmlwidgets
          any::webshot2

          
    - name: Run R script
      run: |
        Rscript cricmatches.R  # Run the R script located in the root directory
    - name: Commit results
      run: |
        git config --local user.email "actions@github.com"
        git config --local user.name "GitHub Actions"
        git add daily_conversion_rates.csv
        git commit -m 'Data updated' || echo "No changes to commit"
        git push -u origin main
